### PR TITLE
feat: graceful shutdown of metrics collector

### PR DESCRIPTION
**Pull request by hawi74**

### CODE REVIEW

**Review by bendiknesbo — APPROVED** [review]

**Review by nhhagen — APPROVED** [review]
Awsome

**Comment by nhhagen** [comment]
@bendiknesbo abd @hawi74 should we make `NewDatadogMetrics()` and/or the `NewBaseMetricCollector()` return no-op variants in the environment variable `DD_DISABLE`is set to `true`?

**Comment by hawi74** [comment]
@nhhagen sure. It would be much better than checking `if m.DatadogMetrics == nil || m.DatadogMetrics.GetClient() == nil` on every call. Also, creating metrics collector by passing the reuslt of `NewDatadogMetrics` to `NewBaseMetricCollector` may result in storing a typed nil under `BaseMetricCollector.DatadogMetrics`, which renders the above check useless. Returning a no-op collector instead should fix the problem.

**Comment by nhhagen** [comment]
@hawi74 do you have time to fix it?

**Pull request merged**
